[package]
name = "ruint-simd"
version = "0.1.0"
edition = "2021"

[dependencies]
ruint = "1.12.1"

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }

[[bench]]
name = "add_bench"
harness = false
